name: finstar cd

on:
  push:
    branches: [main]

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        python-version: [3.9] # [3.8, 3.9]
        poetry-version: [1.1.7]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install poetry ${{ matrix.poetry-version }}
        run: |
          python -m ensurepip
          python -m pip install --upgrade pip
          python -m pip install poetry==${{ matrix.poetry-version }}

      - name: View poetry --help
        run: poetry --help

      - name: Install dependencies
        shell: bash
        run: python -m poetry install --no-root

      - name: Run checks
        run: |
          python -m poetry run tox -e check

      - name: Run tests
        run: |
          python -m poetry run tox -e test

      - name: Build package
        if: startsWith( github.ref, 'refs/tags/v')
        run: |
          python -m poetry build

      - name: Publish package to PyPI
        if: startsWith( github.ref, 'refs/tags/v')
        env:
          USER: __token__
          PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          python -m poetry publish -u "$USER" -p "$PASSWORD"
